### ISSUE TITLE
Оформление репозитория

### ISSUE THREAD

**Issue by TorinAsakura** [atls/hyperion#426]
### С чем связан запрос на фичу?

Хочется конкурировать в узких кругах с такими фреймворками как bootstrap, material-ui, getuikit

### Расскажите как вы это себе видите

Полагаю, нужно сформулировать дальнейшую стратегию оформления и продвижения либы с непосредственными пользователями и клиентами.

К примеру, для разработчиков было бы важным иметь возможность "развернуть" стенд с имеющимися компонентами в одну команду типа:

```
yarn demo
```

Для клиента, к примеру, было бы круто потыкать наш uikit на собственном домене типа https://ui.atls.team на подобии https://getuikit.com

### Приложите примеры реализаций

https://getuikit.com -> https://github.com/uikit/uikit
http://getbootstrap.com - > https://github.com/twbs/bootstrap

**Comment by taqyon** [comment]
@TorinAsakura слушай а ты не думал дать ему имя? ui kit'у

**Comment by taqyon** [comment]
@TorinAsakura проект для русскоязычных? Или иностранный? Какой язык использовать?

**Comment by TorinAsakura** [comment]
@taqyon Думал, как и всем своим проектам, пока не занимался этим вопросам. Думал что-то с корнем for, или fuse. Пока хз

**Comment by TorinAsakura** [comment]
@taqyon ru/en

**Comment by taqyon** [comment]
> @taqyon Думал, как и всем своим проектам, пока не занимался этим вопросам. Думал что-то с корнем for, или fuse. Пока хз

предлагаю Atlas

>@taqyon ru/en

Давай тогда остановимся на ru пока, после вехи посмотрим можно ли перейти на en

**Comment by atls-github** [comment]
Статус?

**Comment by TFK70** [comment]
Часть трекается тут - https://github.com/atls/uikit/issues/428

@TorinAsakura @taqyon в целом скажите что это за задача: её можно закрыть или здесь еще есть TBD топики?

**Comment by TorinAsakura** [comment]
@TFK70 да, тут надо добить ридми, бейджи, в общем как у больших ребят

**Comment by TorinAsakura** [comment]
@TFK70 статус?

**Comment by TFK70** [comment]
> @TFK70 статус?

В сабтасках весь прогресс

**Comment by atls-github** [comment]
Статус?

**Comment by TorinAsakura** [comment]
в процессе

**Comment by atls-github** [comment]
Статус?

**Comment by atls-github** [comment]
Статус?

**Comment by TorinAsakura** [comment]
Возобновлена

**Comment by atls-github** [comment]
Статус?

**Comment by atls-github** [comment]
Статус?

**Comment by Nelfimov** [comment]
В очереди

**Comment by atls-github** [comment]
Статус?

**Comment by Nelfimov** [comment]
В очереди

**Comment by atls-github** [comment]
Статус?

**Comment by Nelfimov** [comment]
В очереди

**Comment by atls-github** [comment]
Статус?

**Comment by atls-github** [comment]
Таске месяц. Закрыта за утратой актуальности.

**Comment by atls-github** [comment]
Статус?

**Comment by Nelfimov** [comment]
В очереди

**Comment by atls-github** [comment]
Статус?

**Comment by atls-github** [comment]
Статус?

**Comment by archeon-atls** [comment]
Таске месяц. Закрыта за утратой актуальности.
