### ISSUE TITLE
UI KIT Repo Content

### ISSUE THREAD

**Issue by taqyon** [atls/hyperion#428]
Тикет инспирирован #426.

## Документы

- [ ] Readme
	- [x] #429
	- [x] #432
	- [x] #433
	- [x] #435
	- [ ] Contributing (link to contribute md file)
	- [x] #436
	- [x] #437
	- [ ] Copyright & License
- [ ] Code of conduct
- [ ] Contributing
- [ ] External Link To Deployed Resource
- [ ] Repo Tags
- [ ] Repo About

---

- https://tailwindcss.com/

**Comment by atls-github** [comment]
Статус?

**Comment by atls-github** [comment]
Статус?

**Comment by TFK70** [comment]
В очереди

**Comment by atls-github** [comment]
Статус?

**Comment by TorinAsakura** [comment]
@vodopmi проверить на соответствие

**Comment by vodopmi** [comment]
> @vodopmi проверить на соответствие

не зная об этой задаче, я обновил и этот репозиторий, когда оформлением всех репозириев занимались.

**total**: в репе свежие ридми, ковёр. мы утверждали с тобой

**Comment by TorinAsakura** [comment]
@vodopmi В настройках гитхаба, должны появится новые фичи для превью. Включи пожалуйста новый вид репозиториев.

**Comment by atls-github** [comment]
Статус?

**Comment by atls-github** [comment]
Статус?

**Comment by atls-github** [comment]
Статус?

**Comment by atls-github** [comment]
Таске месяц. Закрыта за утратой актуальности.
