### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by taqyon** [atls/hyperion#432]
# Примеры

## Several quick start options are available:

- [Download the latest release](https://github.com/twbs/bootstrap/archive/v5.2.0-beta1.zip)
- Clone the repo: git clone https://github.com/twbs/bootstrap.git
- Install with [npm](https://www.npmjs.com/): npm install bootstrap@v5.2.0-beta1
- Install with [yarn](https://yarnpkg.com/): yarn add bootstrap@v5.2.0-beta1
- Install with [Composer](https://getcomposer.org/): composer require twbs/bootstrap:5.2.0-beta1
- Install with [NuGet](https://www.nuget.org/): CSS: Install-Package bootstrap Sass: Install-Package bootstrap.sass

Read the [Getting started page](https://getbootstrap.com/docs/5.2/getting-started/introduction/) for information on the framework contents, templates, examples, and more.

## Getting started

You have the following options to get UIkit:

- Download the [latest release](https://github.com/uikit/uikit/releases/latest) with pre-built CSS and JS.
- Install with [npm](https://npmjs.com/) to get all source files as they are available on GitHub: npm install uikit
- Install with [yarn](https://yarnpkg.com/) to get all source files as they are available on GitHub: yarn add uikit
- Directly load UIkit from [jsDelivr](https://www.jsdelivr.com/): https://www.jsdelivr.com/package/npm/uikit
- Clone the repo to get all source files including build scripts: git clone git://github.com/uikit/uikit.git

**Comment by taqyon** [comment]
@TorinAsakura этот пункт весьма прозаичный. И надо чтобы написал его либо ты, либо кто-то другой (инженер). Потому что здесь тупо всегда пошаговая инструкция чё делать.

**Comment by atls-github** [comment]
Статус?

**Comment by TFK70** [comment]
@TorinAsakura первая ревизия - https://github.com/atls/uikit/wiki/%D0%9D%D0%B0%D1%87%D0%B0%D0%BB%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B

Нужно от тебя ревью: пожелания, требования

Вообще я считаю, что такие документы нужно писать на английском, так как они уже используются не только для команды. Русифицировать тоже можно, но после того как будет готова инглиш версия. Что скажешь?

**Comment by atls-github** [comment]
Статус?

**Comment by TFK70** [comment]
@TorinAsakura жду комментов по [этому](https://github.com/atls/uikit/issues/432#issuecomment-1296502458)

**Comment by TorinAsakura** [comment]
> @TorinAsakura жду комментов по [этому](https://github.com/atls/uikit/issues/432#issuecomment-1296502458)

- используй аски, вместо скриншотов, как это сделано у всех ребят
- "По умолчанию Hyperion не предоставляет готовые компоненты, так как его цель - стандартизация и упрощение процесса их сборки" - нарушена подчинительная связь - "цель гипериона - стандартизация и упрощение процесса" - "поэтому он не предоставляет готовые компоненты…"
- для блока с прототипами и генераторами я бы тоже добавил по примеру
- для блока лучших практик я бы добавил примеров

Важно помнить, что наша аудитория не обязательно должна быть с IQ >90 поэтому нужно писать так, чтобы можно было максимально просто войти

**Comment by atls-github** [comment]
Статус?

**Comment by TFK70** [comment]
В очереди
