### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by taqyon** [atls/hyperion#435]
Секция про документацию. У UIkit'а её нет. У бутстрапа есть и выглядит вот так: 

## Documentation

Bootstrap's documentation, included in this repo in the root directory, is built with [Hugo](https://gohugo.io/) and publicly hosted on GitHub Pages at <https://getbootstrap.com/>. The docs may also be run locally.

Documentation search is powered by [Algolia's DocSearch](https://community.algolia.com/docsearch/). Working on our search? Be sure to set `debug: true` in `site/assets/js/search.js`.

### Running documentation locally

1. Run `npm install` to install the Node.js dependencies, including Hugo (the site builder).
2. Run `npm run test` (or a specific npm script) to rebuild distributed CSS and JavaScript files, as well as our docs assets.
3. From the root `/bootstrap` directory, run `npm run docs-serve` in the command line.
4. Open `http://localhost:9001/` in your browser, and voilà.

Learn more about using Hugo by reading its [documentation](https://gohugo.io/documentation/).

### Documentation for previous releases

You can find all our previous releases docs on <https://getbootstrap.com/docs/versions/>.

[Previous releases](https://github.com/twbs/bootstrap/releases) and their documentation are also available for download.

---

Я считаю что такая секция нужна если у hyperion будет свой домен с докой. В ином случае не вижу смысла.

**Comment by atls-github** [comment]
Статус?

**Comment by atls-github** [comment]
Статус?

**Comment by TFK70** [comment]
@TorinAsakura набросал "генезис" документации, посмотри - https://github.com/atls/uikit/wiki/%D0%9D%D0%B0%D1%87%D0%B0%D0%BB%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B

**Comment by atls-github** [comment]
Статус?

**Comment by TorinAsakura** [comment]
> @TorinAsakura набросал "генезис" документации, посмотри - https://github.com/atls/uikit/wiki/%D0%9D%D0%B0%D1%87%D0%B0%D0%BB%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B

а я ведь тебе уже ревью оставлял где-то, не помнишь в какой задаче? Я там всё достаточно чётко расписал

**Comment by TFK70** [comment]
> > @TorinAsakura набросал "генезис" документации, посмотри - https://github.com/atls/uikit/wiki/%D0%9D%D0%B0%D1%87%D0%B0%D0%BB%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B
> 
> а я ведь тебе уже ревью оставлял где-то, не помнишь в какой задаче? Я там всё достаточно чётко расписал

Да, я до сих пор на почте это храню чтобы не забыть

**Comment by atls-github** [comment]
Статус?

**Comment by atls-github** [comment]
Статус?
