### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by taqyon** [atls/hyperion#436]
В этой секции обычно лежат ссылки на соц сети: 
- дискорд сервер
- ссылка на github discussions
- твитер
- etc

Если есть что-то уже из списка или что-то другое — кидай.

**Comment by atls-github** [comment]
Статус?

**Comment by TFK70** [comment]
@TorinAsakura приложи ссылки которые мы будем паблить, если они есть

**Comment by atls-github** [comment]
Статус?

**Comment by TFK70** [comment]
Создали коммьюнити дискорд сервер - https://discord.gg/RR2hfaJ9

Позже здесь будет обсуждение его оформления и т.п.

**Comment by atls-github** [comment]
Статус?

**Comment by TorinAsakura** [comment]
@bbbaso есть примерное понимание когда мы закончим идентику для нашего uikit?

**Comment by bbbaso** [comment]
> есть примерное понимание когда мы закончим идентику для нашего uikit?

Я честно говоря мучался с этим ворп прыжком в лого, его толком никак не отобразить в векторе (много зависит от палитры и бг) + нет рефов даже близко (все напоминает кометы, ракеты и тд).

@TorinAsakura может стоит просто другую идею рассмотреть? Потрачу сам на это сегодня время, прикину варианты от себя

**Comment by TorinAsakura** [comment]
@bbbaso Так и сделай комету, ворп это летащий на скоростях объект

**Comment by bbbaso** [comment]
@TorinAsakura 

Добавил 3 [варианта](https://www.figma.com/file/z6Tt1Metg1nFBgchVEW2Ql/All-identity?node-id=752%3A508&t=D3OfIpq42ESgQ3ZE-4)

**Comment by TorinAsakura** [comment]
> @TorinAsakura
> 
> Добавил 3 [варианта](https://www.figma.com/file/z6Tt1Metg1nFBgchVEW2Ql/All-identity?node-id=752%3A508&t=D3OfIpq42ESgQ3ZE-4)

не то

https://yootheme.com/blog/tag/Warp вот отличный пример "прыжка" только нам нужно больше частиц энергии исходящей отрисовать, а тебя слишком плотно прилегает к объекту прыжка

**Comment by atls-github** [comment]
Статус?

**Comment by atls-github** [comment]
Статус?
