### ISSUE TITLE
Layers

### ISSUE THREAD

**Issue by TFK70** [atls/hyperion#464]
### С чем связан запрос на фичу?

Добавить popover и переписать tooltip

### Расскажите как вы это себе видите

```typescript
import { useState } from 'react'
import { useLayer } from 'react-laag'

const usePopover = (placement, offset = 9, trigger = 'click') => {
  const [isOpen, setOpen] = useState<boolean>(false)

  const close = () => setOpen(false)

  const { layerProps, triggerProps, renderLayer } = useLayer({
    isOpen,
    placement,
    auto: true,
    onOutsideClick: close,
    onDisappear: close,
    triggerOffset: offset,
  })

  const setTrigger = (value) => {
    if (value === 'click') {
      return { ...triggerProps, onClick: () => setOpen(!isOpen) }
    }
    if (value === 'hover') {
      return {
        ...triggerProps,
        onMouseEnter: () => setOpen(true),
        onMouseLeave: () => setOpen(false),
      }
    }

    return {}
  }

  const render = (children) => renderLayer(isOpen && children)

  return {
    triggerProps: setTrigger(trigger),
    layerProps: {
      ...layerProps,
      style: {
        ...layerProps.style,
      },
    },
    render,
    isOpen,
    setOpen,
  }
}

export { usePopover }

```

**Comment by Amiditin** [comment]
@Nelfimov, в этой таске мне нужно пофиксить [Popover](https://ui.atls.design/?path=/story/proto_components-popover--base) и добавить реализацию Tooltip и Popover в виде хуков?

**Comment by Nelfimov** [comment]
Да. Так же выделить в отдельный слой стили:

```typescript
...
      style: {
        ...layerProps.style,
      },
...
```

**Comment by Nelfimov** [comment]
> 1. Стоит ли выносить хук [useTooltip](https://github.com/atls/hyperion/blob/feat/upgrade-tooltip-and-popover/ui-parts/tooltip/src/use-tooltip.hook.tsx) в папку hooks?

Можно. Главное экспортировать и корневого index.ts

> 2. Можешь привести пример реализации, когда пропсы children и container функции ([типизация](https://github.com/atls/hyperion/blob/bd74834a7b73be5c23462d5bbbe6721bc5ad498a/ui-parts/tooltip/src/tooltip.interfaces.ts#L13-L15))? Просто не понимаю как тултип в этом случае должен себя вести.

https://github.com/torin-asakura/drum-in/blob/d7463823418cef64da77edc79d6145fd5e8758a4/ui/utils/src/components/repeater/repeater.component.tsx#L16

> 3. Когда мы пробрасываем triggerProps в children, они перекрывают уже имеющиеся пропсы ([строка](https://github.com/atls/hyperion/blob/bd74834a7b73be5c23462d5bbbe6721bc5ad498a/ui-parts/tooltip/src/tooltip.component.tsx#L21C10-L21C70)), т.е. к примеру console.log ниже не сработает. Это нужно исправлять?
> 
> ```tsx
> export const Example = () => (
>   <Tooltip text='test' trigger='click' animate>
>     <TestButton onClick={() => console.log('CLick')}>Base</TestButton>
>   </Tooltip>
> )
> ```

Самый частый пример на что это может влиять - кнопка закрытия тултипа. Но ведь она работает у тебя в stories для поповера, нет?

**Comment by Amiditin** [comment]
> Самый частый пример на что это может влиять - кнопка закрытия тултипа. Но ведь она работает у тебя в stories для поповера, нет?

Ты про эту [строчку](https://github.com/atls/hyperion/blob/bd74834a7b73be5c23462d5bbbe6721bc5ad498a/ui-proto/popover/src/popover.stories.tsx#L74)? Тут же в контент пробрасывается метод close, а не вешается onClick на TestButton.
```tsx
<Layout mt={50}>
  {render({ title: 'Title', content: <TestContent onClick={close} /> })}
  <TestButton {...triggerProps}>Hook</TestButton>
</Layout>
```

**Comment by Amiditin** [comment]
> Я пока не предвижу сценариев где этот баг мог бы влиять на функционал.

К примеру, здесь Tooltip не будет открываться
```tsx
export const Example = () => {
  const [isOpen, setIsOpen] = useState(false)

  return (
    <Tooltip isOpen={isOpen} text='test' trigger='click' animate>
      <TestButton onClick={() => setIsOpen(!isOpen)}>Base</TestButton>
    </Tooltip>
  )
}
```

**Comment by Nelfimov** [comment]
Для кнопок же триггером будет `hover`, а иначе как построить сценарий использования?

Возможен такой сценарий: первый клик - показать тултип, второй - произвести `onClick`. Но это вроде неинтуитивно. Поэтому пока не вижу с этим проблем.
