### ISSUE TITLE
Добавление пакета utils

### ISSUE THREAD

**Issue by eshevlyakova** [atls/hyperion#468]
### С чем связан запрос на фичу?

Из проекта в проект копипаститься папка utils с различным набором вспомогательных функций и хуков

### Расскажите как вы это себе видите

Оформить папку utils как пакет, который будет содержать различные часто используемые хуки (например useHover) и вспомогательные функции

**Comment by TorinAsakura** [comment]
Найди все подобные утилиты и закинь ссылки на них сюда в виде списка

**Comment by eshevlyakova** [comment]
Часто используется это:
1. https://github.com/delta-doc/web/blob/master/ui/utils/src/hooks/use-hover.hook.ts
2. https://github.com/torin-asakura/drum-in/blob/master/ui/utils/src/hooks/use-popover.hook.ts

Остальное добавляется в зависимости от проекта и реализации:

1. https://github.com/torin-asakura/drum-in/blob/master/ui/utils/src/helpers/capitalize.helper.ts

**Comment by atls-github** [comment]
Статус?

**Comment by Nelfimov** [comment]
Сделано: https://github.com/atls/hyperion/pull/483
