### ISSUE TITLE
Грейд версий зависимостей `button`

### ISSUE THREAD

**Issue by Nelfimov** [atls/hyperion#484]
### С чем связан запрос на фичу?

Обновление пировых зависимостей под актуальные

### Расскажите как вы это себе видите

Необходимо прогрейдить зависимости `@atls-ui-parts/button`, `@atls-ui-proto/button` под актуальные пакеты.

Важное примечание:
пакеты `@emotion` оставить на версии 11.9.х.

### Definition of done (критерий готовности)

`yarn check` проходит без ошибок, версии обновлены до максимально последних, истории с компонентом работают.

**Comment by MakhovRoman** [comment]
@Nelfimov Я правильно понимаю порядок действий:

- обновляю версии зависимостей в  `peerDependencies` до актуальных, к примеру, `"react": "^17.0.1"` --> `"react": "^18.2.0"`
- выполняю проверку `yarn check`
- проверяю работоспособность истории с компонентом
- создаю ветку `feat/button-peerdependencies ` и делаю PR в ветку `master` ?

**Comment by Nelfimov** [comment]
@MakhovRoman все верно. Только:
- откажись от "^"
- ревью ПР запрашивай сначала у меня

**Comment by MakhovRoman** [comment]
Перед  PR -  мне нужно в `yarn.lock` обновлять версии зависимостей? В документации сказано, что ничего самостоятельно с ним делать нельзя - поэтому решил уточнить.

Раньше со Storybook не сталкивался, поэтому возник вопрос - для проверки работоспособности истории мне нужно запустить скрипт `"dev": "start-storybook --config-dir ./src -p 3000"` из папки `ui/design`?

**Comment by Nelfimov** [comment]
> Перед PR - мне нужно в `yarn.lock` обновлять версии зависимостей? В документации сказано, что ничего самостоятельно с ним делать нельзя - поэтому решил уточнить.

`yarn.lock` вручную не редактируем. Он генерится команде `yarn` и автообновляется при изменении зависимостей через `yarn`.
 
> Раньше со Storybook не сталкивался, поэтому возник вопрос - для проверки работоспособности истории мне нужно запустить скрипт `"dev": "start-storybook --config-dir ./src -p 3000"` из папки `ui/design`?

Скрипт `dev` - верный. Запускать **design** из того места, где ты провел изменения. Т.е. сделал изменения в `parts` - соответственно нужен оттуда же **design**

**Comment by MakhovRoman** [comment]
Финальный вопрос (я на это очень надеюсь) - для публикации ветки через протокол SSH мне нужно:
- [x] Сгенерировать ключ SSH
- [x] Добавить его в настройках в раздел  `SSH keys`
- [x] Добавить в  SSH-агент и проверить командой `ssh -T git@github.com`
- [ ]  Находясь в каталоге с репозиторием изменить удаленную точку следующим образом: `git remote set-url origin git@github.com:MakhovRoman/hyperion.git` ?

**Comment by Nelfimov** [comment]
Да. Только если ты клонировал репу через SSH, то все должно и так работать.

Попробуй пуш свою ветку в качестве эксперимента.

**Comment by MakhovRoman** [comment]
Попробовал `git push --set-upstream origin chore/button-peerdependencies` - выдало ошибку:
<details>
<summary>Error logs</summary>

```text
Username for 'https://github.com': MakhovRoman
Password for 'https://MakhovRoman@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/atls/hyperion.git/'
```
</details>


Потом я ввел команду `git remote -v` и получил следующее:

<details>
<summary>Remote logs</summary>

```
origin  https://github.com/atls/hyperion.git (fetch)
origin  https://github.com/atls/hyperion.git (push)
```
</details>

**Comment by TorinAsakura** [comment]
> Попробовал `git push --set-upstream origin chore/button-peerdependencies` - выдало ошибку:
> 
> Error logs
> ```
> Username for 'https://github.com': MakhovRoman
> Password for 'https://MakhovRoman@github.com': 
> remote: Support for password authentication was removed on August 13, 2021.
> remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
> fatal: Authentication failed for 'https://github.com/atls/hyperion.git/'
> ```
> 
> Потом я ввел команду `git remote -v` и получил следующее:
> 
> Remote logs
> ```
> origin  https://github.com/atls/hyperion.git (fetch)
> origin  https://github.com/atls/hyperion.git (push)
> ```
> 
> UPD: команда `git remote set-url origin git@github.com:atls/hyperion.git` решила проблему

не понятно что ты вообще делаешь…
процесс проходит следующим образом:
- git clone git@github.com:org/repo.git
- вносишь правки
- git add . && git commit -m "type: msg" или yarn commit
- git push origin type/branch-name

Всё. Никакой магии и никаких ремоутов.
