### ISSUE TITLE
Вопросы по выполнению задачи https://github.com/atls/hyperion/issues/492

### ISSUE THREAD

**Issue by AlinaLaniuk** [atls/hyperion#495]
### Область

Апргрейд зависимостей

### Описание

Не понимаю некоторых моментов по выполнению таски.
При обновлении пакета ui-parts/sidebar падает ошибка.

### Воспроизведение

1. иду в воркспейс 
2. yarn workspace @atls-ui-parts/sidebar add framer-motion@latest.
3. падает ошибка, пакет не обновляется

### Ожидаемое поведение

Обновление пакета, отсутствие ошибок после команд yarn check и yarn test unit

### Логи

```shell
(node:23650) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Usage Error: Package "framer-motion" is already listed as a regular dependency - remove the -D,-P flags or remove it from your dependencies first

$ yarn add [--json] [-F,--fixed] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
```

### Действия

Обновляю пакеты так:

1. иду в пакет @atls-ui-parts/sidebar
2. команда yarn workspace <имя воркспейса> add <--dev --peer или без флага, если нужно обновить обычные зависимости> <имя пакета>@latest.
3. после обновления всех пакетов, иду в корневую директорию проекта, устанавливаю по новой зависимости, делаю yarn check и yarn test unit

### Вопрос

**По ошибке:**

- При обновлении @atls-ui-parts/sidebar падает ошибка.
Ну и то же самое при попытке обновить пир зависимости. Что с этим делать?

**Также не понимаю несколько моментов, помогите.**

- При обновлении peerDependencies в пакетах появляется знак *.

Пример (воркспейс @atls-ui-parts/upload):
  "devDependencies": {
    "@atls-ui-parts/avatar": "workspace:^",
    "@types/node": "20.5.7",
    "@types/react": "18.2.21",
    "graphql": "16.8.0",
    "react": "18.2.0"
  },
  "peerDependencies": {
    "graphql": "*",
    "react": "*"
  }
Я не понимаю, это значит "версия пакета такая же, как указана выше в devDependencies" или "версия пакета такая же, как указана у ''родителя". Так оставлять можно? Или указывать пакет ручками?

- В таске указано, что версии должны быть жесткими. Когда команда yarn add с тегом latest отрабатывает, автоматически указывается диапазон. Правильно понимаю, что сделать версию жесткой - значит просто убрать руками ^ ?

- Не понимаю, что делать с зависимостями на воркспейс. Например, при обновлении devDependencies @atls-ui-parts/upload зависимость на @atls-ui-parts/avatar выглядит так:

  "devDependencies": {
    "@atls-ui-parts/avatar": "workspace:^",
  },
Если я правильно понимаю, это значит, что будет взята версия, которая указана в package.json соответствующего пакета и выше. Но опять же, как правильно сделать? Прописать руками последнюю версию пакета жестко?

- В критериях готовности указано: yarn check проходит без ошибок, версии обновлены до максимально последних, истории design с компонентом работают. Что означает вот эта часть: **истории design с компонентом работают**?

**Comment by SlumberyDude** [comment]
@AlinaLaniuk 
Пиши вопросы не в новой задаче, а в комментарии к [старой](https://github.com/atls/hyperion/issues/492). Ща посмотрю что у тебя с задачей, пока что закрой этот issue и продублируй сообщение в комментарий оригинальной задачи пожалуйста.
