### ISSUE TITLE
Фикс `publish action`

### ISSUE THREAD

**Issue by Nelfimov** [atls/hyperion#498]
### Описание бага

Во время выполнения `publish` в `Actions` ошибка с версиями у `button-generator`.

### Воспроизведение

1. Перейти в [`Actions`](https://github.com/atls/hyperion/actions)
2. Слева выбрать `Publish`

### Ожидаемое поведение

Экшен прошел без ошибок.

### Материалы

https://github.com/atls/hyperion/actions/runs/6043277003

### Данные окружения

Github

**Comment by Nelfimov** [comment]
Необходимо по npmjs.com проверить опубликованные версии пакетов и сравнить их с локальными в мастере. Если не совпадает, брать версию с npmjs.com.

**Comment by kalininatonya** [comment]
> Необходимо по npmjs.com проверить опубликованные версии пакетов и сравнить их с локальными в мастере. Если не совпадает, брать версию с npmjs.com.

Так и сделала, в npmjs.com  - 0.0.14, локально было 0.0.13

**Comment by Nelfimov** [comment]
А остальные пакеты проверила?

**Comment by kalininatonya** [comment]
> npmjs.com

Неа, тк ты только про button-generator писал. Проверить?

**Comment by Nelfimov** [comment]
@kalininatonya Да, могут быть везде ошибки

**Comment by kalininatonya** [comment]
> @kalininatonya Да, могут быть везде ошибки

Вроде все, глянь  потом ПР, пожалуйста
