### ISSUE TITLE
Обновление зависимостей `events-state`, `hidden-input`

### ISSUE THREAD

**Issue by Nelfimov** [atls/hyperion#508]
### С чем связан запрос на фичу?

Необходимо обновить зависимости под актуальные пакеты

### Расскажите как вы это себе видите

Необходимо прогрейдить все зависимости `@atls-ui-parts` у `hidden-input` `events-state`.

Важное примечание:

- пакеты @emotion оставить на версии 11.9.х.
- не использовать ^, только жесткие версии

### Definition of done (критерий готовности)

`yarn check` проходит без ошибок, версии обновлены до максимально последних, истории `design` с компонентом работают.

**Comment by absolemDev** [comment]
При установке зависимостьей ошибка:
```
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0001: │ Error: EACCES: permission denied, open '/home/absolemdev/dev/atlsTeam/hyperion/.yarn/install-state.gz'
➤ YN0000: └ Completed in 0s 761ms
```
Чем лечится?

**Comment by Nelfimov** [comment]
проверь доступ к файлу по указанному пути - походу ни чтения не редактирования у тебя нет.

**Comment by Nelfimov** [comment]
> Хотелось бы поподробнее про этот процесс:
> 
> > истории design с компонентом работают

В репозитории есть `storybook`, напр. https://github.com/atls/hyperion/tree/master/ui-parts/design

Надо убедиться что если у компонентов есть "истории" - они работают в `storybook`

> И с этим что можно сделать?
> 
> > (node:10294) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. ...

Нет, это сообщения нашего ярн бандла.

**Comment by absolemDev** [comment]
https://github.com/atls/hyperion/pull/510
