### ISSUE TITLE
`ui-parts/datepicker` не экспортирует интерфейсы и не дает работать с `react-datepicker`

### ISSUE THREAD

**Issue by Nelfimov** [atls/hyperion#509]
### Описание бага

При установке `@atls-ui-parts/datepicker` как зависимость в наши проекты компонент не дает работать с пропсами `react-datepicker` не смотря на экспорт этого интерфейса.

### Воспроизведение

1. Установить в проект зависимость `@atls-ui-parts/datepicker`
2. Использовать компонент в любом фрагменте/странице
3. Пропсы `react-datepicker` недоступны к выбору и редактированию

### Ожидаемое поведение

Пропсы поддаются редактированию, IDE знает о них и дает автоподстановку.

### Материалы

https://reactdatepicker.com

В качестве проекта для экспериментов можно воспользоваться https://github.com/torin-asakura/drum-in

### Данные окружения

- Chrome 117.0.5938.92 (Official Build) (arm64)

**Comment by Nelfimov** [comment]
Ошибка в том, что `react-datepicker` не получает react-dom, хотя ожидает в `peerDependencies`.

Соответственно попробуй:
1. В зависимостях `landing-banner` добавь в пир зависимости `react-dom: *`
2. Если не поможет, то надо добавить в `.yarnrc.yml` такую штуку как `packageExtension`.Некоторые библиотеки плохо работают с `yarn pnp` поэтому приходится вручную такое прописывать. Пример можешь посмотреть в рутовом `yarnrc.yml`

**Comment by FrankJaskon** [comment]
Получилось запустить. 

Как я понимаю, вот у нас объявление интерфейса параметром, которые ожидает `Datepicker`

```
import { ReactDatePickerProps } from 'react-datepicker'
import { DatepickerStyles }     from './styles'
export interface DatepickerProps extends DatepickerStyles, ReactDatePickerProps {}
```

Проблема в том, что **ReactDatePickerProps** из библиотеки `@types/react-datepicker` не отрабатывает нормально при установке `@types/react-datepicker`.

Пока получилось решить проблему следующим образом:

1. Добавить в `.yarnrc.yml` следующие зависимости:
``` 
  '@atls-ui-parts/datepicker@*':
    dependencies:
      react-dom: '*'
      '@types/react-datepicker': '*'
```
2. Установить зависимости `yarn add @atls-ui-parts/datepicker@0.0.17 @emotion/css@11.11.2`

После этого типизация на компоненте Datepicker отрабатывает нормально, видны пропсы из обоих интерфейсов - DatepickerStyles, ReactDatePickerProps

**Comment by FrankJaskon** [comment]
@Nelfimov 
> Попробуй посмотри может что-то с версией самого react-datepicker, возможно есть обновление или наоборот надо снизить версию.

В компоненте используется `4.16.0` версия для компонента и `4.15.0` для типов. Уже вышли более новые версии, последние версии - `4.21.0` и `4.19.1` соответственно. 

> Для теста рекомендую скопировать наш @atls-ui-parts/datepicker в любой из проектов и экспортировать его оттуда. А дальше - экспериментировать и смотреть что не так.

Пока я попробовал скопировать файлы `@atls-ui-parts/datepicker` в проект, обновить и установить зависимости. И уже в фрагменте импортировать этот компонент, но получаю ошибку: `TS2307: Cannot find module '@ui/datepicker' or its corresponding type declarations.`  

Завтра попробую разобраться как правильно подключить и запустить компонент и попробую обновить react-datepicker до последних версий.

**Comment by Nelfimov** [comment]
Все правильно. Как «починишь», проверь что проект запускается и билдится. Скрипты билдов можешь посмотреть в package.json энтрипоинта и в нашей репе tools

**Comment by FrankJaskon** [comment]
@Nelfimov Запустил в проекте https://github.com/torin-asakura/drum-in с обновленными до последних версий зависимостями `react-datepicker` и `@types/react-datepicker`.

Вот `package.json` файл **Datepicker**, где видно все версии, которые я использовал:

```
{
  "name": "@ui/datepicker",
  "version": "0.0.1",
  "main": "src/index.ts",
  "dependencies": {
    "date-fns": "2.22.1",
    "react-datepicker": "4.21.0"
  },
  "devDependencies": {
    "@emotion/css": "11.9.0",
    "@emotion/styled": "11.9.3",
    "@types/react": "17.0.47",
    "@types/react-datepicker": "4.19.1",
    "@types/styled-system": "5.1.17",
    "@ui/input": "workspace:*",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "styled-system": "5.1.5"
  },
  "peerDependencies": {
    "@emotion/css": "11.9.3",
    "@emotion/styled": "11.9.3",
    "react": "18.2.0",
    "react-dom": "*",
    "styled-system": "5.1.5"
  }
}
```
Из основного: 
- добавил ` "react-dom": "18.2.0"` в dev-зависимости, т.к в обратном случае всегда получал ошибку о том, что у потомков нет доступа к `react-dom`.
- использовал "@types/react": "17.0.47" т.к по факту ни `yarn add -D @types/react@18.2.21`, ни правка версии в самом файле `package.json` не давала никаких результатов. Среда подсказывала, что все одно используется версия `17.0.47`.
- понизил минорную версию `"@emotion/css": "11.9.0"` т.к `11.9.3` не находилась при установке

После этого снова добавил его в фрагмент **landing-banner** и из `landing/entrypoints/renderer` вызвал скрипты `yarn dev, yarn build, yarn prepack, yarn start`.  Все прошли успешно, я проверил, все логи совпадают с запуском проекта без `datepicker`. Локально проект тоже запускается и в **dev** и через **start**.

На всякий случай, вот сами скрипты, которые вызывал:
```
"scripts": {
    "build": "yarn next build src --no-lint && cp -r ./src/.next/standalone ./dist && cp -r ./src/.next/static ./dist/.next/static && mv ./dist/server.js ./dist/index.js",
    "dev": "yarn next dev src",
    "prepack": "run build",
    "start": "node dist/index.js"
 },
```

**Comment by Nelfimov** [comment]
Проверь еще этим скриптом: https://github.com/atls/tools#проверка-проекта-на-ошибки

Также для `peer` у `react-dom` зафиксируй конкретную версию.

**Comment by FrankJaskon** [comment]
@Nelfimov 
> Проверь еще этим скриптом: [https://github.com/atls/tools#проверка-проекта-на-ошибки](https://github.com/atls/tools#%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0-%D0%BD%D0%B0-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8)

Получаю ошибку при выполнении этих скриптов:

```
[@landing/renderer-entrypoint]: Process started
[@landing/renderer-entrypoint]: ➤ YN0000: Package workspace @landing/renderer-entrypoint to /tmp/71534d6b7297082975a43a713cd6f01e
[@landing/renderer-entrypoint]: ➤ YN0036: Calling the "prepack" lifecycle script
[@landing/renderer-entrypoint]: ➤ YN0036: Prepack script failed (exit code 1, logs can be found here: /tmp/xfs-521a1eb3/prepack.log); run yarn prepack to investigate
[@landing/renderer-entrypoint]: ➤ YN0000: Failed with errors in 12s 2ms
[@landing/renderer-entrypoint]: Process exited (exit code 1), completed in 12s 91ms
```
Остальные блоки выполняются с 0-м статусом.

Эти скрипты падают из-за `yarn prepack`. Видно, что страницы билдятся, но в самом конце возникает ошибка:

`mv: не удалось выполнить stat для './dist/server.js': Нет такого файла или каталога`

Если скопировать репозиторий https://github.com/torin-asakura/drum-in с нуля, ничего не менять в нём и вызвать `yarn prepack`, то поведение будет идентичным, вот лог из терминала:

```
Page                                       Size     First Load JS
┌ ○ / (1803 ms)                            13.8 kB         492 kB
├   /_app                                  0 B             152 kB
├ ○ /404                                   194 B           152 kB
├ ○ /connacol (1607 ms)                    13 kB           497 kB
├ ○ /contact (1553 ms)                     2.04 kB         404 kB
├ ○ /contract-offer (2341 ms)              1.37 kB         404 kB
├ ○ /feeling-of-time (1430 ms)             9.28 kB         493 kB
├ ○ /fifth-dimension (1789 ms)             9.29 kB         493 kB
├ ○ /opening-the-rhythm (2354 ms)          11.2 kB         495 kB
├ ○ /polyrhythmic-keys (1521 ms)           8.63 kB         487 kB
├ ○ /privacy-policy (1427 ms)              1.37 kB         404 kB
└ ○ /seventh-heaven (1626 ms)              9.29 kB         493 kB
+ First Load JS shared by all              152 kB
  ├ chunks/framework-43a01f45f7b7f91c.js   45.2 kB
  ├ chunks/main-f109b3f4b62201a7.js        27.7 kB
  ├ chunks/pages/_app-59b4bb40e195bf77.js  77.3 kB
  ├ chunks/webpack-313269b132d0cb8d.js     1.7 kB
  └ css/76c5cb97e761fa8e.css               605 B

○  (Static)  automatically rendered as static HTML (uses no initial props)

mv: не удалось выполнить stat для './dist/server.js': Нет такого файла или каталога
```

При этом, если выполнить `yarn start`, то он запустится без ошибок и будет слушать `localhost:3000`

**Comment by Nelfimov** [comment]
> @Nelfimov
> 
> > Проверь еще этим скриптом: [https://github.com/atls/tools#проверка-проекта-на-ошибки](https://github.com/atls/tools#%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0-%D0%BD%D0%B0-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8)
> 
> Получаю ошибку при выполнении этих скриптов:
> 
> ```
> [@landing/renderer-entrypoint]: Process started
> [@landing/renderer-entrypoint]: ➤ YN0000: Package workspace @landing/renderer-entrypoint to /tmp/71534d6b7297082975a43a713cd6f01e
> [@landing/renderer-entrypoint]: ➤ YN0036: Calling the "prepack" lifecycle script
> [@landing/renderer-entrypoint]: ➤ YN0036: Prepack script failed (exit code 1, logs can be found here: /tmp/xfs-521a1eb3/prepack.log); run yarn prepack to investigate
> [@landing/renderer-entrypoint]: ➤ YN0000: Failed with errors in 12s 2ms
> [@landing/renderer-entrypoint]: Process exited (exit code 1), completed in 12s 91ms
> ```
> 

Если то что ты вывел ниже, это логи из `/tmp/xfs-521a1eb3/prepack.log`, то все норм.

Эту ошибку можно игнорировать.

**Comment by FrankJaskon** [comment]
@Nelfimov 
> Если то что ты вывел ниже, это логи из /tmp/xfs-521a1eb3/prepack.log, то все норм.
> Эту ошибку можно игнорировать.

Да, в логах `/tmp/xfs-521a1eb3/prepack.log` та же ошибка, что я писал выше:  

`mv: не удалось выполнить stat для './dist/server.js': Нет такого файла или каталога`

Вот последний конфиг `package.json` с зафиксированной версией для **peer** `react-dom`:
```
{
  "name": "@ui/datepicker",
  "version": "0.0.1",
  "main": "src/index.ts",
  "dependencies": {
    "date-fns": "2.22.1",
    "react-datepicker": "4.21.0"
  },
  "devDependencies": {
    "@emotion/css": "11.9.0",
    "@emotion/styled": "11.9.3",
    "@types/react": "17.0.47",
    "@types/react-datepicker": "4.19.1",
    "@types/styled-system": "5.1.17",
    "@ui/input": "workspace:*",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "styled-system": "5.1.5"
  },
  "peerDependencies": {
    "@emotion/css": "11.9.3",
    "@emotion/styled": "11.9.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "styled-system": "5.1.5"
  }
}
```

Мне нужно что-то ещё делать по этой задаче?

**Comment by Nelfimov** [comment]
Поправь только `dev` зависимости у `react` и `react-dom`. В этом проекте скорее всего в руте стоит резолюшн на эти пакеты чтобы были 17 версии, однако нам этот пакет использовать в проектах где уже 18 реакт. Поэтому типы нужны соответствующие.

**Comment by Nelfimov** [comment]
"Все правильно сделал"
