### ISSUE TITLE
Локализация стилей `react-datepicker` в `@atls-ui-parts/datepicker`

### ISSUE THREAD

**Issue by Nelfimov** [atls/hyperion#514]
### С чем связан запрос на фичу?

Библиотека идет с необходимостью импортировать ее собственные `css` стили. Чтобы это не делать вручную в каждом проекте, надо их локализовать в нашем пакете.

### Расскажите как вы это себе видите

- [x] Все содержимое файлов стилей переносим в локальный `react-datepicker.styles.ts`
- [x] Эти стили применяем к тегу контейнера, которым оборачиваем компонент `react-datepicker`
- [x] Тестируем на `design`, запускаем и проверяем что стили есть на странице. Можно искать по классам

- [x] Доп. опция - можно указать буленовский пропс для нашего компонента, чтобы был выбор подгружать стоковые стили или нет.

### Definition of done (критерий готовности)

Стили загружается на странице с нашим компонентом.

### Приложите пример реализаций

<details>

<summary>X.styles.ts</summary>

```tsx
import { styleFn } from 'styled-system'

export const insertableColor = 'FFF1EB'
export const insertableNotMatchedColor = 'DCF6E0'

const createBaseStyles = (): styleFn => () => ({
  '&#editor': {
    border: 'none',
    margin: 0,
    padding: 0,
    overflow: 'scroll',
    overflowX: 'hidden',
    backgroundColor: 'transparent',
    backgroundClip: 'padding-box',
    borderRadius: 4,
  },

  '.ProseMirror': {
    position: 'relative',
    wordWrap: 'break-word',
    whiteSpace: 'break-spaces',
    padding: '4px 8px 4px 14px',
    lineHeight: 1.2,
    outline: 'none',
    WebkitFontVariantLigatures: 'none',
    fontVariantLigatures: 'none',
    fontFeatureSettings: `"liga" 0` /* the above doesn't seem to work in Edge */,
  },

  ...
})

export const baseStyles = createBaseStyles()
```

</details>

<details>

<summary>container.component.ts</summary>

```tsx
import styled                                 from '@emotion/styled'

import { baseStyles }                         from './container-style.styles'

const Container = styled.div(
  baseStyles,
)

export { Container }
```

</details>

### Приложите материалы задачи

https://github.com/Hacker0x01/react-datepicker/tree/main/src/stylesheets

**Comment by Nelfimov** [comment]
Обрати внимание - стили уже прописаны: https://github.com/atls/hyperion/blob/master/ui-parts/datepicker/src/styles/base/base.styles.ts

Надо их обновить.

**Comment by FrankJaskon** [comment]
@Nelfimov 

Стили обновил, но пока не могу проверить, что они применились корректно из-за того, что в этом пункте:

> Тестируем на design, запускаем и проверяем что стили есть на странице. Можно искать по классам

Падают ошибки при выборе Datepicker в сторибуке:

```
GET https://ui-parts.ui.atls.design/main.cc2dcb75.iframe.bundle.js net::ERR_ABORTED 404 (Not Found)

iframe.html:1 Refused to execute script from 
'https://ui-parts.ui.atls.design/main.cc2dcb75.iframe.bundle.js' 
because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

Проверял на текущем проекте из master без моих локальных изменений - тоже самое поведение.

Запускал из папки `design` через `yarn prepack yarn start` и через `yarn dev`.

**Comment by Nelfimov** [comment]
Давай попробуем в другом проекте, например `drum-in` где ты уже тестировал апгрейд версий.

**Comment by TorinAsakura** [comment]
![Снимок экрана 2023-10-25 в 15 34 23](https://github.com/atls/hyperion/assets/3940885/9d7a3822-0965-4d33-b414-4c8653ee901d)
https://ui-parts.ui.atls.design/?path=/story/components-datepicker--datepicker

**Comment by FrankJaskon** [comment]
@TorinAsakur

![Снимок экрана от 2023-10-25 15-40-01](https://github.com/atls/hyperion/assets/84450082/4f7648b0-1519-43ec-83b1-b41450843d94)

**Comment by FrankJaskon** [comment]
@Nelfimov 

> Давай попробуем в другом проекте, например drum-in где ты уже тестировал апгрейд версий.

Так и сделал, обновил стили и проверил загружаются ли они. Также добавил в интерфейс `AppearanceStyles` необязательный пропс загрузки базовых стилей. И уже через этот пропс вызывается `createAndInjectDatepickerStyles` в компоненте, объявил его по умолчанию в `true`, чтобы сохранить совместимость. 
```
  const { baseStyle = true } = props

  useEffect(() => {
    baseStyle && createAndInjectDatepickerStyles(props)
  }, [props])
```
Т.к не могу полноценно протестировать через сторибук, я пока сделал `ПР` с `WIP` коммитом, чтобы было видно что и как я делаю.

**Comment by Nelfimov** [comment]
Все верно. Только помимо фикса чеков проверь интерфейсы - твой новый пропс не объявлен для самого компонента.

**Comment by FrankJaskon** [comment]
@Nelfimov 

> Все верно. Только помимо фикса чеков проверь интерфейсы - твой новый пропс не объявлен для самого компонента.

Видимо, это из-за `push --force` он потерялся. Вернул пропс, ошибки линтера исправил.

**Comment by Nelfimov** [comment]
А зачем это ты пользуешься форсом?? 🤔

**Comment by FrankJaskon** [comment]
@Nelfimov 

Я залил ветку, но ещё не делал `PR`. Увидел, что опечатался в названии переменной и через `git commit -S --amend` сделал коммит, чтобы не создавать из-за одной буквы новый коммит, т.к ветку никто не смотрел ещё и `PR` не создавал, я сделал форс. Но он очень странно отработал, буду тогда через новый коммит делать, чтобы наверняка.

**Comment by Nelfimov** [comment]
Работай с гитом через IDE - можно же и переименовать, и ребейз интерактивный сделать.

Что угодно лишь бы без форсов. Форсы разрешены только при ребейзе.

**Comment by TorinAsakura** [comment]
> @Nelfimov
> 
> Я залил ветку, но ещё не делал `PR`. Увидел, что опечатался в названии переменной и через `git commit -S --amend` сделал коммит, чтобы не создавать из-за одной буквы новый коммит, т.к ветку никто не смотрел ещё и `PR` не создавал, я сделал форс. Но он очень странно отработал, буду тогда через новый коммит делать, чтобы наверняка.

а зачем ты добавляешь ключ для подписи? ты до всех пор не настроил автоподпись?

**Comment by FrankJaskon** [comment]
@TorinAsakura 

> а зачем ты добавляешь ключ для подписи? ты до всех пор не настроил автоподпись?

Я здесь написал так, чтобы было видно, что коммит точно подписывается и не было вопросов. У меня настроено автоматическое добавление подписи `GPG` через `webstorm` и выполнение `git log`  с опцией `--show-signature`
