### ISSUE TITLE
Добавить `Image` из `next` в `@atls-ui-parts/image`

### ISSUE THREAD

**Issue by Nelfimov** [atls/hyperion#518]
### С чем связан запрос на фичу?

Необходимо добавить компонент `Image` из `next`

### Расскажите как вы это себе видите

- [x] Создать отдельный компонент с зависимостью от `next`, пока что край 12.3.4
- [x] Стилизовать его

### Definition of done (критерий готовности)

Компонент создан, работает в других проектах

**Comment by atls-github** [comment]
Статус?

**Comment by Nelfimov** [comment]
В очереди

**Comment by atls-github** [comment]
Статус?

**Comment by Nelfimov** [comment]
В очереди

**Comment by atls-github** [comment]
Статус?
