### ISSUE TITLE
Задача на проработку репозитория

### ISSUE THREAD

**Issue by Nelfimov** [atls/hyperion#519]
### С чем связан запрос на фичу?

Необходимо облагородить наш репозиторий тестами и нехватающими компонентами

### Расскажите как вы это себе видите

- [ ] Покрыть тестами все наши компоненты. Краткий гайд по тестированию [раз](https://css-tricks.com/front-end-testing-is-for-everyone/), [два](https://blog.logrocket.com/end-to-end-testing-react-jest-puppeteer/)
- [ ] Сделать тесты генераторов на файлах а не на текстовой константе
- [ ] Пройтись по нашим проектам и посмотреть есть ли компоненты и утилиты которых нет в этом репозитории

На каждый компонент/утилиту/тест - отдельная таска, ветка и ПР.

### Definition of done (критерий готовности)

Все виджеты покрыты тестами, из проектов перенесены часто используемые компоненты и утилиты

**Comment by atls-github** [comment]
Статус?

**Comment by atls-github** [comment]
Таске месяц. Закрыта за утратой актуальности.
