### ISSUE TITLE
Дополнить `text-transform` новой фичей

### ISSUE THREAD

**Issue by oksssvv** [atls/hyperion#524]
### С чем связан запрос на фичу?

Добавить функционал скрытия длинного текста

### Расскажите как вы это себе видите

В `ui` компонент `text-transform` необходимо прикрутить дополнительный функционал скрытия длинного заголовка / текста

### Приложите пример реализаций

варианты реализации скрытия длинного и среднего текстового сообщения:
```

hidePartLongTitle = (text: string): string => {
  if (text !== undefined && text.length > 53) return `${text.slice(0, 50)}...`  
  return text
}
```

```

hidePartMiddleTitle = (text: string): string => text.length > 48? `${text.slice(0, 45)}...` : text

```

**Comment by Nelfimov** [comment]
Тебе же по силам самой такое сделать

**Comment by oksssvv** [comment]
@Nelfimov 

>Тебе же по силам самой такое сделать

ну оукей, сделаю, просто ты сказал на тебя завести)

**Comment by atls-github** [comment]
Статус?

**Comment by Nelfimov** [comment]
> * оптимальное ли это количество символов, после которого идет скрытие или же использовать не булеан, а приходящий аргумент ввиде числа

Кол-во символов лучше получать в аргументах в виде числа.

> * и подходящий ли нейминг пропса я подобрала?
> 
> ```
> 
>    switch (key) {
>         case 'lowerCase':
>           return result.toLowerCase()
>         case 'upperCase':
>           return result.toUpperCase()
>         case 'firstLetter':
>           return result.substr(0, 1)
>         case 'lastLetter':
>           return result.substr(-1)
>         case 'substr':
>           return Array.isArray(args) ? result.substr(args[0], args[1]) : result.substr(args)
>         case 'replace':
>           return result.replace(args[0], args[1])
> ->     case 'partHiding':
> ->       return `${result.slice(0, 45)}...`
>         default:
>           return result
>       }
> ```

Можешь `hideAfter` например
