### ISSUE TITLE
Снести `stitches`

### ISSUE THREAD

**Issue by Nelfimov** [atls/hyperion#545]
### С чем связан запрос на фичу?

`stitches` больше не поддерживается разработчиком, поэтому надо убрать его из проекта. Компоненты использующие его - рефактор на использование `emotion`.

### Расскажите как вы это себе видите

- [ ] удалить зависимости от `stitches`
- [ ] рефактор на `emotion`

### Definition of done (критерий готовности)

`Stitches` в проекте больше нет, все компоненты используют `emotion`

**Comment by archeon-atls** [comment]
Статус?

**Comment by Nelfimov** [comment]
в очереди

**Comment by archeon-atls** [comment]
Статус?

**Comment by Nelfimov** [comment]
в очереди

**Comment by archeon-atls** [comment]
Статус?

**Comment by Nelfimov** [comment]
в очереди

**Comment by archeon-atls** [comment]
Статус?

**Comment by Nelfimov** [comment]
В очереди

**Comment by archeon-atls** [comment]
Статус?

**Comment by Nelfimov** [comment]
в очереди

**Comment by archeon-atls** [comment]
Статус?

**Comment by Nelfimov** [comment]
в очереди

**Comment by archeon-atls** [comment]
Статус?

**Comment by Nelfimov** [comment]
в очереди

**Comment by TorinAsakura** [comment]
Ститч используется только в пакете core, который, в свою очередь используется только в аватаре, ничего при этом не ломая и не нагружая, это почистим в следующем релизе когда будем переезжать на стайлекс/ваниллу
