### ISSUE TITLE
`vanilla/extract`: изучить возможность использования у нас

### ISSUE THREAD

**Issue by Nelfimov** [atls/hyperion#546]
# Сводка

Новая библиотека `css-in-js`

# Мотивация

Библиотека позволяет уйти от операций в рантайме, но оставаясь в парадигме `css-in-js`

# Дизайн в деталях

Это основная часть RFC. Объясните дизайн достаточно подробно. Это должно касаться специфики и ключевых моментов, а также включать примеры того, как используется эта функция. Любая новая терминология должна быть
определена здесь.

# Недостатки

- пока не замечено 

# Альтернативы

[`stylex`](https://stylexjs.com)

# Стратегия адаптации

- протестировать на одном компоненте, в том числе использовав в одном из наших проектов
- добавить в конфиг [бандлера](https://vanilla-extract.style/documentation/getting-started)

# Как мы будем этому обучать

- через примеры использования. Разница между `emotion` и `vanilla-extract` небольшая.

**Comment by archeon-atls** [comment]
Статус?

**Comment by Nelfimov** [comment]
в очереди

**Comment by archeon-atls** [comment]
Статус?

**Comment by Nelfimov** [comment]
в очереди

**Comment by archeon-atls** [comment]
Статус?

**Comment by Nelfimov** [comment]
в очереди

**Comment by Amiditin** [comment]
> протестировать на одном компоненте, в том числе использовав в одном из наших проектов

Прочитав доку [vanilla/extract](https://vanilla-extract.style/documentation/getting-started/), попробовал создать базовую версию кнопки из Candify [`ButtonElement`](https://github.com/candify-tech/web/blob/20bfb517e4f9c890217e01cc39f6f3cc5c5606b6/ui/button/src/button.component.tsx#L20), получившейся код: [vanilla-extract.zip](https://github.com/atls/hyperion/files/14878752/vanilla-extract.zip). 

Поэтапно:
1. Добавил по [гайду](https://vanilla-extract.style/documentation/integrations/next/#nextjs) в `next.config.js` плагин `createVanillaExtractPlugin`
2. Создал глобальную тему на основе уже имеющейся в candify, и импортировал в энтрипоинт по [гайду](https://vanilla-extract.style/documentation/global-api/create-global-theme/). Проверил в дев и билд версиях css переменные создаются.
3. Создал `apperience` и `shape` стили по структуре напоминающие гиперионовские
```ts
const appearanceBlueDefaultStyles = createAppearanceStyles({
  fontColor: vars.colors.button.blue.default.font,
  backgroundColor: vars.colors.button.blue.default.background,
  borderColor: vars.colors.button.blue.default.border,
})

const mediumStyles = createShapeStyles({
  size: 40,
  rounding: vars.radii.f24,
})
```
4. Воспользовался [`@vanilla-extract/recipes`](https://vanilla-extract.style/documentation/packages/recipes/) для создание разных вариантов состояния конпки:
```ts
export const buttonStyles = recipe({
  base: baseStyles,

  variants: {
    variant: appearanceVariant,
    hover: appearanceHover,
    pressed: appearancePressed,
    disabled: appearanceDisabled,
    size: shapeStyles,
  },

  defaultVariants: {
    variant: 'blue',
    size: 'medium',
  },
})

```
5. Прокидываю получившиеся стили состояний в `className` кнопки:
```tsx
<button
  className={buttonStyles({
    size,
    variant,
    pressed: pressed ? `${variant}Pressed` : undefined,
    hover: hover ? `${variant}Hover` : undefined,
    disabled: disabled ? `${variant}Disabled` : undefined,
  })}
  ...
```

По сути, вышел рабочий вариант `ButtonElement`, который может автоматически генерировать типы для пропсов, указанных в `variants`, благодаря [RecipeVariants](https://vanilla-extract.style/documentation/packages/recipes/#recipevariants). Переписать гиперионовкий генератор стилей для кнопок, думаю, будет не сложно, тк по структуре почти тоже самое. 

Для добавления локальных свойств у получившейся кнопки, например фиксированная ширина, нужно будет создавать локальный класс, либо же попробовать создать отдельный [sprinkles](https://vanilla-extract.style/documentation/packages/sprinkles/#usage) для кнопки. В теории, можно будет ограничить доступные для редактирования свойства, и получать их через пропсы в runtime через [Sprinkles](https://vanilla-extract.style/documentation/packages/sprinkles/#sprinkles).

> Недостатки

- Значениями для ключей у темы могут быть только строчки
```ts
type Tokens = {
    [key: string]: string | Tokens;
};
```
- Прокидывать кастомные пропсы в компонент, чтобы достать их в стилях и как-то использовать, те аналоги prop, ifProp, `switchProp`, явного такого функционала не нашел. Но, по идее, как замену можно использовать фунции обертки, либо же пакет [`@vanilla-extract/recipes`](https://vanilla-extract.style/documentation/packages/recipes/).

**Comment by Nelfimov** [comment]
@Amiditin теперь давай попробуем реализовать то же самое со stylex и сравним. 

Нам важно следующее:
- удобство и максимальная совместимость с нашим текущим подходом, особенно с темой 
- Работа в nextjs без use client
- Минимум операций в рантайме

**Comment by TorinAsakura** [comment]
@Nelfimov И пожалуйста, делай пры, не надо прикреплять архивы

**Comment by Nelfimov** [comment]
@Amiditin https://github.com/atls-lab/frontend

**Comment by archeon-atls** [comment]
Статус?

**Comment by archeon-atls** [comment]
Статус?

**Comment by Nelfimov** [comment]
в работе

**Comment by archeon-atls** [comment]
Статус?

**Comment by Nelfimov** [comment]
в очереди

**Comment by archeon-atls** [comment]
Статус?

**Comment by Nelfimov** [comment]
В оереди

**Comment by Nelfimov** [comment]
@aliceinapple @Amiditin обновите статус плиз

**Comment by Amiditin** [comment]
> обновите статус плиз

Работаю в ветке [feat/vanilla-extract](https://github.com/atls-lab/frontend/tree/feat/vanilla-extract), добавлена глобальная тема `vanilla/extract`, `Button` и `Text` компоненты. В работе универсальные свойства, аналоги `space` `layout` `typography` из `styled-system`.

**Comment by aliceinapple** [comment]
@Amiditin сориентируй пожалуйста над чем сейчас работаешь и что еще осталось?

**Comment by aliceinapple** [comment]
что сделано:

- добавлены базовые стили для инпута
- добавлен компонент инпут

**Comment by Amiditin** [comment]
@aliceinapple FYI

#### Что сделано:
- Переход с `@vanilla-extract/sprinkles` на [`rainbow-sprinkles`](https://github.com/wayfair/rainbow-sprinkles). Таким образом, решаем проблему с динамическими пропсами не завязанных на теме `width`, `height` и тд, и определением всех доступных свойств для пропса не через их перечисление `flexDirection: ['row', 'column']`, а передавая булевое значение `flexDirection: true`
- Добавлены универсальные свойства `space` `layout` `flexbox` `typography`
- Добавлен базовый компонент `Box` на основе перечисленных свойств выше
#### Что дальше:
- Добавить оставшиеся универсальные свойства `color` `position` `boxShadow` и тд
- Доделать компонент `Box` на основе новых универсальных свойств
- Добавить компоненты `Layout` `Column` `Row` `Grid`

**Comment by Nelfimov** [comment]
@Amiditin @aliceinapple обязательно в конце перехода проверьте сторибуки для компонентов.

**Comment by aliceinapple** [comment]
#### Что сделано:
- Добавлены компоненты `link` `image` `scrollbar`
#### Что дальше:
- Доработать добавленные компоненты
- Использовать [rainbow-sprinkles](https://github.com/wayfair/rainbow-sprinkles) где необходимо

**Comment by Amiditin** [comment]
@aliceinapple FYI

#### Что сделано:
- Удалена `emotion` тема, теперь только `vanilla/extract`
- Добавлены универсальные свойства `border`, `color`, `grid`, `position`, `shadow`
- Добавлены компоненты  `Layout` `Column` `Row` `Grid`
#### Что дальше:
- Добавить универсальные свойства и дефолтные пропсы для `Text` и `Button` компонентов
- Добавить `Space` и `Currency` компоненты, аналоги `@atls-ui-parts/text` компонентам

**Comment by aliceinapple** [comment]
#### Что сделано:
- Рефактор компонентов `link` и `image` (использование `rainbow-sprinkles`)
#### Что дальше:
- Добавить компонент `select`

**Comment by Amiditin** [comment]
#### Что сделано:
- Доработаны `Text` и `Button` компоненты
- Добавлены `Space` и `Currency` компоненты для `@ui/text`
- Добавлен `Condition` компонент
#### Что дальше:
- Подтянуть ветку @aliceinapple 
- Добавить компонент `Autocompolete` из [hyperion](https://ui.atls.design/?path=/story/proto_components-autocomplete--base)

**Comment by aliceinapple** [comment]
#### Что сделано:
- Добавлен компонент `select`
#### Что дальше:
- Доработать`select`
- Добавить `switch`
- Пообщаться с @Amiditin по поводу дальнейших действий

**Comment by aliceinapple** [comment]
#### Что сделано:
- Добавлен компонент `switch`
#### Что дальше:
- Доработать`select` и `switch`
- Добавить `modal`, `divider`

**Comment by Amiditin** [comment]
#### Что сделано:
- Добавлен компонент `Autocompolete`
#### Что дальше:
- Добавить `Progress` и `Tooltip` компоненты
- Проработать сторибуки для добавленных компонентов

**Comment by Amiditin** [comment]
#### Что сделано:
- Добавлены `Progress` и `Tooltip` компоненты
#### Что дальше:
- Проработать сторибуки для добавленных компонентов

**Comment by Amiditin** [comment]
#### Что сделано:
- Добавлен [storybook](https://storybook.js.org) последней версии, для совместимости с `@vanilla/extract`  [docs](https://storybook.js.org/recipes/@vanilla-extract/css)
- Добавлен `stories` для `Tooltip`
#### Что дальше:
- Добавить остальные `stories` для компонентов

@Nelfimov для нас важно, чтобы `stories` лежали рядом с компонентами? или продолжать их в модуле storybook создавать [ссылка](https://github.com/atls-lab/frontend/blob/90eb7f44c60057d878e330c2a24b83ae41cb65a5/ui/design/stories/tooltip/tooltip.stories.tsx)? При первом варианте падают ошибки, когда пытаюсь выйти за пределы модуля, и мне не особо нравится, что в таком случае для некоторых модулей, например [`@atls-ui-parts/tooltip`](https://github.com/atls/hyperion/blob/387e54b38d1d4a9d393fe206525ada5742d89231/ui-parts/tooltip/package.json#L16), создаются дополнительные ненужные зависимости, например `@atls-ui-parts/layout`

<details>

![image](https://github.com/atls/hyperion/assets/80476878/2a4d3bff-e8dc-41a1-8fad-a80aaeaa3f3c)
 </details>

**Comment by Nelfimov** [comment]
> @Nelfimov для нас важно, чтобы `stories` лежали рядом с компонентами?

Так нагляднее - компонент, а рядом история как использовать.



> При первом варианте падают ошибки, когда пытаюсь выйти за пределы модуля, и мне не особо нравится, что в таком случае для некоторых модулей, например [`@atls-ui-parts/tooltip`](https://github.com/atls/hyperion/blob/387e54b38d1d4a9d393fe206525ada5742d89231/ui-parts/tooltip/package.json#L16), создаются дополнительные ненужные зависимости, например `@atls-ui-parts/layout`

Ты же их добавляешь в дев зависимости, поэтому все норм.

Какие ошибки падают?

**Comment by Amiditin** [comment]
> Какие ошибки падают?

В консоли такая, толком не разбирался ещё

```
ERROR in ../../.yarn/__virtual__/@ui-layout-virtual-f4b5a3b82e/1/ui/layout/src/box/box.css.ts
Module build failed (from ../../.yarn/__virtual__/@vanilla-extract-webpack-plugin-virtual-468c0998f7/0/cache/@vanilla-extract-webpack-plugin-npm-2.3.11-96bc4d2d50-b18b88d4dc.zip/node_modules/@vanilla-extract/webpack-plugin/loader/dist/vanilla-extract-webpack-plugin-loader.cjs.js):
ModuleNotFoundError: Module not found: Error: rainbow-sprinkles tried to access @vanilla-extract/dynamic (a peer dependency) but it isn't provided by your application; this makes the require call ambiguous and unsound.

Required package: @vanilla-extract/dynamic
Required by: rainbow-sprinkles@virtual:ff71f372cc3486cd89139b4eb0299a0e09ec87afe363215d1cf0bec88448af55e5437e150b268a8c04ac7dec287bc7bcdc966d8a5f5241163b71aafe4e73c8d8#npm:0.17.2 (via /home/amiditin/React/frontend/.yarn/__virtual__/rainbow-sprinkles-virtual-f52254f2fa/0/cache/rainbow-sprinkles-npm-0.17.2-66dba8755c-9ca84affe2.zip/node_modules/rainbow-sprinkles/dist/)
Ancestor breaking the chain: @app/home-page@workspace:pages-router/pages/home
Ancestor breaking the chain: @ui/autocomplete@workspace:ui/autocomplete
Ancestor breaking the chain: @ui/button@workspace:ui/button
Ancestor breaking the chain: @ui/image@workspace:ui/image
Ancestor breaking the chain: @ui/input@workspace:ui/input
Ancestor breaking the chain: @ui/layout@workspace:ui/layout
Ancestor breaking the chain: @ui/link@workspace:ui/link
Ancestor breaking the chain: @ui/progress@workspace:ui/progress
Ancestor breaking the chain: @ui/scrollbar@workspace:ui/scrollbar
Ancestor breaking the chain: @ui/select@workspace:ui/select
Ancestor breaking the chain: @ui/switch@workspace:ui/switch
Ancestor breaking the chain: @ui/text@workspace:ui/text
Ancestor breaking the chain: @ui/tooltip@workspace:ui/tooltip
...tracers
 @ ../../.yarn/__virtual__/@ui-layout-virtual-f4b5a3b82e/1/ui/layout/src/grid/grid.component.tsx 86:0-43 94:25-38
 @ ../../.yarn/__virtual__/@ui-layout-virtual-f4b5a3b82e/1/ui/layout/src/grid/index.ts 1:0-33 1:0-33
 @ ../../.yarn/__virtual__/@ui-layout-virtual-f4b5a3b82e/1/ui/layout/src/index.ts 5:0-23 5:0-23
 @ ../tooltip/src/tooltip.stories.tsx 105:0-36 106:0-36 107:0-33 108:0-33 125:42-48 128:38-44 148:42-45 148:86-92 158:42-48 162:38-41 164:38-44 169:105-111 174:106-112 177:106-109 179:38-44 184:108-114 189:109-115 192:107-110 194:38-44 199:108-111 199:152-158 210:42-45 213:38-44 219:101-107 225:101-107 236:42-45 239:38-44 250:42-45 253:38-44 257:48-51 264:42-45 267:38-44 273:108-114 286:42-45 289:38-44 298:106-112
 @ .././ lazy ^\.\/.*$ include: (?%21.*node_modules)(?:(?:^%7C\/%7C(?:(?:(?%21(?:^%7C\/)\.).)*?)\/)(?%21\.)(?=.)[^/]*?\.stories\.(js%7Cjsx%7Cmjs%7Cts%7Ctsx))$ chunkName: [request] namespace object ./tooltip/src/tooltip.stories.tsx ./tooltip/src/tooltip.stories
 @ ./storybook-stories.js 10:11-14:5
 @ ./storybook-config-entry.js 6:0-50 18:31-39 25:2-28:4 25:58-28:3 27:31-39
```

**Comment by Nelfimov** [comment]
@Amiditin это возникает если что-то вынесено за `src`? Похоже на типичную пробелму решаемую `packageExtensions` в `yarnrc.yml`

**Comment by aliceinapple** [comment]
#### Что сделано:
- Добавлены компоненты `divider` и `modal`
- Добавлен `stories` для `modal`
#### Что дальше:
- Добавить `stories` для `select`, `switch`, `input`

**Comment by Amiditin** [comment]
#### Что сделано:
- Добавлены `stories` в локальные папки для `Autocomplete`, `Button`, `Input`, `Progress`, `Select`
#### Что дальше:
- Доработать `stories` для `Button`, `Input`
- Добавить компоненты `Avatar`, `Popover`

**Comment by Nelfimov** [comment]
@Amiditin @aliceinapple оформите пожалуйста план задач для полного завершения таски.

**Comment by Amiditin** [comment]
> оформите пожалуйста план задач для полного завершения таски.

Сейчас переносим основные компоненты из `hyperion`, прогресс примерно такой:

- [x] `autocomplete`
- [ ] `avatar`
- [ ] `button` на доработке 70%
- [ ] `card`
- [ ] `carousel`
- [ ] `checkbox`
- [x] `condition`
- [ ] `datepicker`
- [x] `design`
- [ ] `devider`
- [ ] `hidden-input`
- [x] `image`
- [ ] `input` на доработке 50%
- [x] `layout`
- [x] `link`
- [ ] `modal`
- [ ] `next-image`
- [ ] `parallax`
- [ ] `placeholder`
- [ ] `popover`
- [x] `progress`
- [ ] `scalable-content`
- [x] `select`
- [ ] `sidebar`
- [ ] `swiper`
- [x] `switch`
- [x] `text`
- [x] `theme`
- [x] `tooltip`
- [x] `conditional-render` модуль без стилей
- [x] `dom` модуль без стилей
- [x] `events-state` модуль без стилей
- [x] `mapbox` модуль без стилей
- [x] `portal` модуль без стилей
- [x] `text-transform` модуль без стилей
- [x] `upload` модуль без стилей

@aliceinapple может что-то пропустил, поставь галочки где не хватает

@Nelfimov есть смысл переносить все, либо какие на твой взгляд можно пропустить?

> # Как мы будем этому обучать
> - через примеры использования. Разница между `emotion` и `vanilla-extract` небольшая.

Правильно понимаю, нужно будет ещё написать про переход с `emotion` на `@vanilla/extract` с примерами?

**Comment by Nelfimov** [comment]
> @Nelfimov есть смысл переносить все, либо какие на твой взгляд можно пропустить?

Все

> Правильно понимаю, нужно будет ещё написать про переход с `emotion` на `@vanilla/extract` с примерами?

Если сделаем хорошие сториз, то в этом не будет необходимости.

**Comment by aliceinapple** [comment]
#### Что сделано:
- Добавила `stories` для `switch`
#### Что дальше:
- Доработать `switch` и `stories` для него
- Добавить `stories`  для `divider`
- Добавить компонент `checkbox`

**Comment by Amiditin** [comment]
#### Что сделано:
- Добавлены `Avatar` и `Popover` компоненты
- Исправлена верстка и добавлены типы для `stories`, @aliceinapple обрати внимание на `tags: ['autodocs']` [docs](https://storybook.js.org/docs/writing-stories/tags#built-in-tags)
#### Что дальше:
- Добавить `HiddenInput`, `DividedFields` и `Textarea` для `@ui/input`
- Добавить `GhostButton` и `Content` для `@ui/button`

**Comment by Amiditin** [comment]
#### Что сделано:
- Добавлены `HiddenInput` и `Textarea` для `@ui/input`
#### Что дальше:
- Добавить `DividedFields` для `@ui/input`
- Добавить `GhostButton` и `Content` для `@ui/button`

**Comment by aliceinapple** [comment]
#### Что сделано:
- Добавила `checkbox`
#### Что дальше:
- Доработать  `checkbox`, `switch` и `stories` для них
- Добавить `stories`  для `divider`

**Comment by Amiditin** [comment]
#### Что сделано:
- Доработан`Textarea`
- Добавлен `GhostButton` для `@ui/button`
#### Что дальше:
- Добавить `DividedFields` для `@ui/input`
- Добавить `Content` для `@ui/button`

**Comment by Amiditin** [comment]
#### Что сделано:
- Добавлен`DividedFields` для `@ui/input`
- Добавлен `story` для `GhostButton`
- Добавлен `Content` для `@ui/button`
#### Что дальше:
- Добавить `NextImage`, `Placeholder`, `ScalableContent` компоненты

**Comment by Amiditin** [comment]
#### Что сделано:
- Добавлены `NextImage`, `Placeholder`, `ScalableContent` компоненты
- Добавлены утилиты из `@atls-ui-parts/dom` в `@ui/utils`
#### Что дальше:
- Добавить `stories` для `Placeholder`
- Добавить `Swiper`компонент

**Comment by Amiditin** [comment]
#### Что сделано:
- Добавлен `Swiper`компонент
- Добавлены `stories` для `Placeholder` `Text` `Currency` `Swiper`
#### Что дальше:
- Добавить `Card` `Sidebar` компоненты

**Comment by aliceinapple** [comment]
#### Что сделано:
- Доработаны компоненты `divider`, `switch`, `checkbox`
- Добавлены `stories` для `divider`, `switch`, `checkbox`

**Comment by Amiditin** [comment]
#### Что сделано:
- Добавлен `Card`компонент
- Добавлен `Sidebar`компонент`
#### Что дальше:
- Добавить `Carousel` компонент

**Comment by Amiditin** [comment]
#### Что сделано:
- Добавлен `Carousel` компонент
#### Что дальше:
- Добавить `Datepicker` и `Parallax` компоненты

**Comment by Amiditin** [comment]
#### Что сделано:
- Добавлен `Datepicker` компонент
#### Что дальше:
- Доработать глобальные стили `Datepicker` компонента
- Добавить `Parallax` компоненты

**Comment by Amiditin** [comment]
#### Что сделано:
- Добавлены глобальные стили для `Datepicker` компонента
- Добавлен `Parallax` компонент
#### Что дальше:
- Добавить генератор стилей кнопки из темы в `@ui/button`

**Comment by Amiditin** [comment]
#### Что сделано:
- Добавлен генератор appearance стилей кнопки
#### Что дальше:
- Добавить генератор appearance стилей инпута
- Начать переносить сторибук, тему, компоненты в hyperion

**Comment by Amiditin** [comment]
#### Что сделано:
- Добавлен генератор appearance стилей инпута
- Добавлен генератор иконок с темой vanilla/extract
#### Что дальше:
- Начать переносить сторибук, тему, компоненты в hyperion

@Nelfimov вопросы
- компоненты переносить для каждого своим PR?
- использовать `"type": "module"`?
- менять мажорную или минорную версию, то есть ставить  `"version": "1.0.0"` или `"version": "0.2.0"`?

**Comment by Nelfimov** [comment]
> * компоненты переносить для каждого своим PR?

Нет, одним.

> * использовать `"type": "module"`?

Да. Можешь посмотреть [тут](https://github.com/atls/raijin/blob/master/config/typescript/package.json) как оформлять для публикации.

> * менять мажорную или минорную версию, то есть ставить  `"version": "1.0.0"` или `"version": "0.2.0"`?

1. Это breaking change
2. руками ничего не меняем. После первого мержа в мастер версия сама пропатчится. Надо будет поменять в `/.yarn/versions` с патча на major

**Comment by Nelfimov** [comment]
@Amiditin завтра завершишь?

**Comment by Amiditin** [comment]
> @Amiditin завтра завершишь?

Завтра добью перенос в hyperion, насчёт генератора фигмы думаю ещё день

**Comment by Amiditin** [comment]
#### Что сделано:
- Перенесены модули начиная с `@atls-ui-parts/autocomplete` по `@atls-ui-parts/layout`, и `@atls-ui-parts/theme` `@atls-ui-parts/text-transform` `@atls-ui-parts/upload`
#### Что дальше:
- Перенести оставшиеся модули в `atls-ui-parts`
- Начать переносить модули в `atls-ui-proto`

**Comment by Amiditin** [comment]
#### Что сделано:
- Перенесены остававшиеся модули в `atls-ui-parts`
#### Что дальше:
- Начать переносить модули в `atls-ui-proto`
- Начать переносить модули в `generators`

**Comment by Amiditin** [comment]
#### Что сделано:
- Перенесены остававшиеся модули в `atls-ui-proto` и в `generators`
#### Что дальше:
- Исправить `yarn typecheck`
- Переделать генератор фигмы под тему `vanilla/extract`

@Nelfimov вопросы:
- В `atls-ui-proto` много модулей, которые просто выполняют функцию реэкспорта из `atls-ui-parts` или ничего не добавляя создаёт тот же компонент, что и в дочернем `atls-ui-parts`, например [layout](https://github.com/atls/hyperion/blob/master/ui-proto/layout/package.json) или [autocomplete](https://github.com/atls/hyperion/blob/master/ui-proto/autocomplete/package.json). Зачем нужны такие модули? Можем ли мы их убрать?
- Для чего нужен `atls-ui-admin`? Можем ли мы его убрать?

**Comment by Nelfimov** [comment]
> * В `atls-ui-proto` много модулей, которые просто выполняют функцию реэкспорта из `atls-ui-parts` или ничего не добавляя создаёт тот же компонент, что и в дочернем `atls-ui-parts`, например [layout](https://github.com/atls/hyperion/blob/master/ui-proto/layout/package.json) или [autocomplete](https://github.com/atls/hyperion/blob/master/ui-proto/autocomplete/package.json). Зачем нужны такие модули? Можем ли мы их убрать?

Насколько я помню - это примеры использования из `parts`, которые можно было бы использовать в реальных проектах.

> * Для чего нужен `atls-ui-admin`? Можем ли мы его убрать?

@TorinAsakura нужны ли нам `admin` и `proto`?

**Comment by Nelfimov** [comment]
@Amiditin 
- `admin` - переносим
- `proto` - нет

**Comment by Amiditin** [comment]
#### Что сделано:
- Убрал `atls-ui-proto`, уникальные компоненты из него пересены в `atls-ui-parts`, например `popover`
- Обновлён `atls-ui-admin`, добавлены 2 темы из `vanilla/extract`, и пример с переключателем в `atls-ui-admin/button`
#### Что дальше:
- Обновить `atls-ui-admin/upload`
- Исправить `yarn typecheck`
- Переделать генератор фигмы под тему `vanilla/extract`

**Comment by Nelfimov** [comment]
@Amiditin публикуем сначала гиперион под версией 1.0.0, затем дальше делаем генератор.

Новый гиперион мне нужен для работы с микрофронтами.

**Comment by Amiditin** [comment]
#### Что сделано:
- Обновлён `atls-ui-admin/upload`
#### Что дальше:
- Исправить `yarn typecheck`
- Переделать генератор фигмы под тему `vanilla/extract`

**Comment by Amiditin** [comment]
@Nelfimov обновил ветку, остался один `typecheck`: для воркспейсов падает такая ошибка
```
Error: The project root is ambiguous, but is required to resolve export map entry '.' in file '/home/amiditin/React/hyperion/.yarn/__virtual__/@atls-ui-admin-button-virtual-13ae66b272/1/ui-admin/button/package.json'.
Supply the `rootDir` compiler option to disambiguate.
```
Попытался добавить в `tsconfig` опцию `"rootDir": "./src"`, не помогло. Есть идеи, как можно исправить?

**Comment by Amiditin** [comment]
> @Amiditin дай свою версию бандла

@Nelfimov использовал бандл такой же как и в frontend репер
```bash
$ yarn -v
0.0.1-git.20240126.hash-5bf25ff7
```
